---
spring:
  application.name: ddd-java
  messages.basename: messages-validation, messages
  jackson.serialization:
    indent-output: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: create-drop

server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /error


management:
  endpoints.web:
    base-path: /management
    exposure.include: "*"

sample:
  mail.enable: false
